// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QuitRoom() {
  window['go']['main']['client']['QuitRoom']();
}

export function Broadcast(arg1) {
  window['go']['main']['client']['Broadcast'](arg1);
}

export function Connect(arg1) {
  window['go']['main']['client']['Connect'](arg1);
}

export function CreateRoom(arg1) {
  return window['go']['main']['client']['CreateRoom'](arg1);
}

export function Disconnect() {
  window['go']['main']['client']['Disconnect']();
}

export function EnterRoom(arg1) {
  window['go']['main']['client']['EnterRoom'](arg1);
}

export function GetRoomList() {
  window['go']['main']['client']['GetRoomList']();
}

export function Nick(arg1) {
  window['go']['main']['client']['Nick'](arg1);
}
