// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QuitRoom():void;

export function Broadcast(arg1:string):void;

export function Connect(arg1:string):void;

export function CreateRoom(arg1:string):Promise<boolean>;

export function Disconnect():void;

export function EnterRoom(arg1:string):void;

export function GetRoomList():void;

export function Nick(arg1:string):void;
